export const SESSION_ESTABLISHED = "SESSION_ESTABLISHED";
export const FETCHED_STUDENT_DATA = "FETCHED_STUDENT_DATA";
export const WINDOW_INNER_WIDTH_CHANGED = "WINDOW_INNER_WIDTH_CHANGED";
export const WINDOW_INNER_HEIGHT_CHANGED = "WINDOW_INNER_HEIGHT_CHANGED";
export const MOUSE_DOWN = "MOUSE_PRESSED";
export const MOUSE_UP = "MOUSE_RELEASED";
export const ESTABLISHING_SESSION = "ESTABLISHING_SESSION";
export const FAILED_ESTABLISHING_SESSION = "FAILED_ESTABLISHING_SESSION";
